# Generated by Django 3.0.8 on 2020-08-01 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles',
        ),
    ]
