# Generated by Django 3.0.8 on 2020-08-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200802_0622'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='profiles',
        ),
    ]
