# Generated by Django 3.0.8 on 2020-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_auto_20200809_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='device_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
