pipelines:
  default:
    - step:
        name: Deploy
        deployment: production
        script:
         - pipe: atlassian/ssh-run:0.2.5
           variables:
             SSH_USER: $SSH_USER
             SERVER: $SSH_SERVER
             COMMAND: >
               cd $DEPLOY_DIR &&
               pwd &&
               git checkout --force origin/$BITBUCKET_BRANCH &&
               source venv/bin/activate &&
               pip3 install -r requirements.txt &&
               python3 manage.py collectstatic
