# Generated by Django 3.0.8 on 2020-08-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
