# Generated by Django 3.0.8 on 2020-08-09 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reports.models.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20200802_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='votes',
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to=reports.models.image.PathAndRename('reports/')),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='reports.Report')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'report_votes',
            },
        ),
    ]
