# Generated by Django 3.0.8 on 2020-08-09 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20200809_1014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='reporter',
            new_name='user',
        ),
    ]
