# Generated by Django 3.0.8 on 2020-08-09 23:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0004_auto_20200809_1145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('report', 'user')},
        ),
    ]
